- Added config vars - Added targets: "install" and "installdocs"

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -4,7 +4,44 @@
 ##  Edward Loper
 ############################################################
 
-all: distributions
+##//////////////////////////////////////////////////////////////////////
+## Configuration variables
+##//////////////////////////////////////////////////////////////////////
+
+# Where do man pages and documentation go?
+LIB = /usr/share
+MAN = ${LIB}/man/
+DOC = ${LIB}/doc/
+
+##//////////////////////////////////////////////////////////////////////
+## Makefile
+##//////////////////////////////////////////////////////////////////////
+all: usage
+usage:
+	@echo "Usage:"
+	@echo "  make install -- Install epydoc"
+	@echo "  make installdocs -- Install the documentation for epydoc"
+
+install:
+	python setup.py install
+
+docs: installdocs
+installdocs:
+	@test -e ${MAN} || \
+	    echo "Could not find ${MAN}; check the makefile variables."
+	@test -e ${DOC} || \
+	    echo "Could not find ${DOC}; check the makefile variables."
+	@test -e ${MAN}
+	@test -e ${DOC}
+	test -e doc || ln -s ../doc doc
+	test -e man || ln -s ../man man
+	cp man/*.1 ${MAN}/man1/
+	cp -r doc ${DOC}/epydoc/
+
+##//////////////////////////////////////////////////////////////////////
+## These targets should only be called from
+## the cvs repository (not from distributions).
+##//////////////////////////////////////////////////////////////////////
 
 # Clean.  
 #    - Erase any pyc and pyo files.
@@ -13,7 +50,7 @@ clean:
 	rm -rf build dist MANIFEST
 	rm -f *.pyc epydoc/*.pyc epydoc/*/*.pyc
 	rm -f *.pyo epydoc/*.pyo epydoc/*/*.pyo
-	rm -f doc
+	rm -f doc man 2>/dev/null || true
 
 # Distributions.
 # Build all from scratch; and create links for convenient access.
@@ -27,21 +64,25 @@ bdist: rpmdist windist
 
 # Produce dist/$(NAME)-$(VERSION).tar.gz
 gztardist:
-	rm -f doc; ln -s ../doc doc
+	test -e doc || ln -s ../html doc
+	test -e man || ln -s ../man man
 	python setup.py -q sdist --format=gztar
 
 # Produce dist/$(NAME)-$(VERSION).tar.gz
 zipdist:
-	rm -f doc; ln -s ../doc doc
+	test -e doc || ln -s ../html doc
+	test -e man || ln -s ../man man
 	python setup.py -q sdist --format=zip
 
 # Produce dist/$(NAME)-$(VERSION)-1.noarch.rpm
 # Produce dist/$(NAME)-$(VERSION)-1.src.rpm
 rpmdist:
-	rm -f doc; ln -s ../doc doc
+	test -e doc || ln -s ../html doc
+	test -e man || ln -s ../man man
 	python setup.py -q bdist --format=rpm
 
 # Produce dist/$(NAME)-$(VERSION).win32.exe
 windist:
-	rm -f doc; ln -s ../doc doc
+	test -e doc || ln -s ../html doc
+	test -e man || ln -s ../man man
 	python setup.py -q bdist --format=wininst
